export const USER_LOGOUT = 'USER_LOGOUT';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILURE = 'FORGET_PASSWORD_FAILURE';

export const UPDATE_DETAILS_REQUEST = 'UPDATE_DETAILS_REQUEST';
export const UPDATE_DETAILS_SUCCESS = 'UPDATE_DETAILS_SUCCESS';
export const UPDATE_DETAILS_FAILURE = 'UPDATE_DETAILS_FAILURE';

export const GET_ALL_USER_DETAILS_REQUEST = 'GET_ALL_USER__DETAILS_REQUEST';
export const GET_ALL_USER_DETAILS_SUCCESS = 'GET_ALL_USER__DETAILS_SUCCESS';
export const GET_ALL_USER_DETAILS_FAILURE = 'GET_ALL_USER__DETAILS_FAILURE';
export const RESET_USER_DETAILS = 'RESET_USER_DETAILS';

export const UPDATE_PROFILE_IMAGE_REQUEST = 'UPDATE_PROFILE_IMAGE_REQUEST';
export const UPDATE_PROFILE_IMAGE_SUCESS = 'UPDATE_PROFILE_IMAGE_SUCESS';
export const UPDATE_PROFILE_IMAGE_FAILURE = 'UPDATE_PROFILE_IMAGE_FAILURE';

export const UPDATE_USERNAME_REQUEST = 'UPDATE_USERNAME_REQUEST';
export const UPDATE_USERNAME_SUCCESS = 'UPDATE_USERNAME_SUCCESS';
export const UPDATE_USERNAME_FAIL = 'UPDATE_USERNAME_FAIL';

export const UPDATE_SOCIAL_ACCOUNT_REQUEST = 'UPDATE_SOCIAL_ACCOUNT_REQUEST';
export const UPDATE_SOCIAL_ACCOUNT_SUCCESS = 'UPDATE_SOCIAL_ACCOUNT_SUCCESS';
export const UPDATE_SOCIAL_ACCOUNT_FAIL = 'UPDATE_SOCIAL_ACCOUNT_FAIL';
