export const LOGIN_REQUEST='LOGIN_REQUEST'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILURE='LOGIN_FAILURE'

export const SIGNUP_REQUEST='SIGNUP_REQUEST'
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS'
export const SIGNUP_FAILURE='SIGNUP_FAILURE'

export const CHANGE_PASSWORD_REQUEST='CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS='CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILURE='CHANGE_PASSWORD_FAILURE'

export const RESET_PASSWORD_REQUEST='RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS='RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE='RESET_PASSWORD_FAILURE'

export const FORGET_PASSWORD_REQUEST='FORGET_PASSWORD_REQUEST'
export const FORGET_PASSWORD_SUCCESS='FORGET_PASSWORD_SUCCESS'
export const FORGET_PASSWORD_FAILURE='FORGET_PASSWORD_FAILURE'

export const FILL_BASIC_DETAILS_REQUEST='FILL_BASIC_DETAILS_REQUEST'
export const FILL_BASIC_DETAILS_SUCCESS='FILL_BASIC_DETAILS_SUCCESS'
export const FILL_BASIC_DETAILS_FAILURE='FILL_BASIC_DETAILS_FAILURE'
