export const GITHUB_O_AUTH = 'GITHUB_O_AUTH';
export const GITHUB_CALLBACK = 'GITHUB_CALLBACK';

export const SAVE_GITHUB_USERNAME_REQUEST = 'SAVE_GITHUB_USERNAME_REQUEST';
export const SAVE_GITHUB_USERNAME_SUCCESS = 'SAVE_GITHUB_USERNAME_SUCESS';
export const SAVE_GITHUB_USERNAME_FAIL = 'SAVE_GITHUB_USERNAME_FAIL';

export const ALL_USER_PROJECTS_REQUEST = 'ALL_USER_PROJECTS_REQUEST';
export const ALL_USER_PROJECTS_SUCCESS = 'ALL_USER_PROJECTS_SUCCESS';
export const ALL_USER_PROJECTS_FAIL = 'ALL_USER_PROJECTS_FAIL';

export const ALL_USER_PROJECTS_BY_ID_REQUEST = 'ALL_USER_PROJECTS_BY_ID_REQUEST';
export const ALL_USER_PROJECTS_BY_ID_SUCCESS = 'ALL_USER_PROJECTS_BY_ID_SUCCESS';
export const ALL_USER_PROJECTS_BY_ID_FAIL = 'ALL_USER_PROJECTS_BY_ID_FAIL';

export const UPDATE_PROJECT_DETAILS_REQUEST = 'UPDATE_PROJECT_DETAILS_REQUEST';
export const UPDATE_PROJECT_DETAILS_SUCCESS = 'UPDATE_PROJECT_DETAILS_SUCCESS';
export const UPDATE_PROJECT_DETAILS_FAIL = 'UPDATE_PROJECT_DETAILS_FAIL';

export const GET_ALL_EDUCATION_LIST_REQUEST = 'GET_ALL_EDUCATION_LIST_REQUEST';
export const GET_ALL_EDUCATION_LIST_SUCCESS = 'GET_ALL_EDUCATION_LIST_SUCCESS';
export const GET_ALL_EDUCATION_LIST_FAIL = 'GET_ALL_EDUCATION_LIST_FAIL';

export const GET_EDUCATION_BY_ID_REQUEST = 'GET_EDUCATION_BY_ID_REQUEST';
export const GET_EDUCATION_BY_ID_SUCCESS = 'GET_EDUCATION_BY_ID_SUCCESS';
export const GET_EDUCATION_BY_ID_FAIL = 'GET_EDUCATION_BY_ID_FAIL';

export const ADD_NEW_EDUCATION_REQUEST = 'ADD_NEW_EDUCATION_REQUEST';
export const ADD_NEW_EDUCATION_SUCCESS = 'ADD_NEW_EDUCATION_SUCCESS';
export const ADD_NEW_EDUCATION_FAIL = 'ADD_NEW_EDUCATION_FAIL';

export const UPDATE_EDUCATION_DETAILS_REQUEST = 'UPDATE_EDUCATION_DETAILS_REQUEST';
export const UPDATE_EDUCATION_DETAILS_SUCCESS = 'UPDATE_EDUCATION_DETAILS_SUCCESS';
export const UPDATE_EDUCATION_DETAILS_FAIL = 'UPDATE_EDUCATION_DETAILS_FAIL';

export const DELETE_EDUCATION_REQUEST = 'DELETE_EDUCATION_REQUEST';
export const DELETE_EDUCATION_SUCCESS = 'DELETE_EDUCATION_SUCCESS';
export const DELETE_EDUCATION_FAIL = 'DELETE_EDUCATION_FAIL';

export const GET_ALL_EXPERIENCE_LIST_REQUEST = 'GET_ALL_EXPERIENCE_LIST_REQUEST';
export const GET_ALL_EXPERIENCE_LIST_SUCCESS = 'GET_ALL_EXPERIENCE_LIST_SUCCESS';
export const GET_ALL_EXPERIENCE_LIST_FAIL = 'GET_ALL_EXPERIENCE_LIST_FAIL';

export const GET_EXPERIENCE_BY_ID_REQUEST = 'GET_EXPERIENCE_BY_ID_REQUEST';
export const GET_EXPERIENCE_BY_ID_SUCCESS = 'GET_EXPERIENCE_BY_ID_SUCCESS';
export const GET_EXPERIENCE_BY_ID_FAIL = 'GET_EXPERIENCE_BY_ID_FAIL';

export const ADD_NEW_EXPERIENCE_REQUEST = 'ADD_NEW_EXPERIENCE_REQUEST';
export const ADD_NEW_EXPERIENCE_SUCCESS = 'ADD_NEW_EXPERIENCE_SUCCESS';
export const ADD_NEW_EXPERIENCE_FAIL = 'ADD_NEW_EXPERIENCE_FAIL';

export const UPDATE_EXPERIENCE_DETAILS_REQUEST = 'UPDATE_EXPERIENCE_DETAILS_REQUEST';
export const UPDATE_EXPERIENCE_DETAILS_SUCCESS = 'UPDATE_EXPERIENCE_DETAILS_SUCCESS';
export const UPDATE_EXPERIENCE_DETAILS_FAIL = 'UPDATE_EXPERIENCE_DETAILS_FAIL';

export const DELETE_EXPERIENCE_REQUEST = 'DELETE_EXPERIENCE_REQUEST';
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS';
export const DELETE_EXPERIENCE_FAIL = 'DELETE_EXPERIENCE_FAIL';

export const GET_ALL_CERTIFICATE_LIST_REQUEST = 'GET_ALL_CERTIFICATE_LIST_REQUEST';
export const GET_ALL_CERTIFICATE_LIST_SUCCESS = 'GET_ALL_CERTIFICATE_LIST_SUCCESS';
export const GET_ALL_CERTIFICATE_LIST_FAIL = 'GET_ALL_CERTIFICATE_LIST_FAIL';

export const GET_CERTIFICATE_BY_ID_REQUEST = 'GET_CERTIFICATE_BY_ID_REQUEST';
export const GET_CERTIFICATE_BY_ID_SUCCESS = 'GET_CERTIFICATE_BY_ID_SUCCESS';
export const GET_CERTIFICATE_BY_ID_FAIL = 'GET_CERTIFICATE_BY_ID_FAIL';

export const ADD_NEW_CERTIFICATE_REQUEST = 'ADD_NEW_CERTIFICATE_REQUEST';
export const ADD_NEW_CERTIFICATE_SUCCESS = 'ADD_NEW_CERTIFICATE_SUCCESS';
export const ADD_NEW_CERTIFICATE_FAIL = 'ADD_NEW_CERTIFICATE_FAIL';

export const UPDATE_CERTIFICATE_DETAILS_REQUEST = 'UPDATE_CERTIFICATE_DETAILS_REQUEST';
export const UPDATE_CERTIFICATE_DETAILS_SUCCESS = 'UPDATE_CERTIFICATE_DETAILS_SUCCESS';
export const UPDATE_CERTIFICATE_DETAILS_FAIL = 'UPDATE_CERTIFICATE_DETAILS_FAIL';

export const DELETE_CERTIFICATE_REQUEST = 'DELETE_CERTIFICATE_REQUEST';
export const DELETE_CERTIFICATE_SUCCESS = 'DELETE_CERTIFICATE_SUCCESS';
export const DELETE_CERTIFICATE_FAIL = 'DELETE_CERTIFICATE_FAIL';

export const RESET_EDUCATION_DETAILS = 'RESET_EDUCATION_DETAILS';
export const RESET_EXPERIENCE_DETAILS = 'RESET_EXPERIENCE_DETAILS';
