export const GITHUB_O_AUTH = 'GITHUB_O_AUTH'
export const GITHUB_CALLBACK = 'GITHUB_CALLBACK'

export const SAVE_GITHUB_USERNAME_REQUEST = 'SAVE_GITHUB_USERNAME_REQUEST'
export const SAVE_GITHUB_USERNAME_SUCCESS = 'SAVE_GITHUB_USERNAME_SUCESS'
export const SAVE_GITHUB_USERNAME_FAIL = 'SAVE_GITHUB_USERNAME_FAIL'

export const ALL_USER_PROJECTS_REQUEST = 'ALL_USER_PROJECTS_REQUEST'
export const ALL_USER_PROJECTS_SUCCESS = 'ALL_USER_PROJECTS_SUCCESS'
export const ALL_USER_PROJECTS_FAIL = 'ALL_USER_PROJECTS_FAIL'


export const ALL_USER_PROJECTS_BY_ID_REQUEST = 'ALL_USER_PROJECTS_BY_ID_REQUEST'
export const ALL_USER_PROJECTS_BY_ID_SUCCESS = 'ALL_USER_PROJECTS_BY_ID_SUCCESS'
export const ALL_USER_PROJECTS_BY_ID_FAIL =    'ALL_USER_PROJECTS_BY_ID_FAIL'

export const UPDATE_PROJECT_DETAILS_REQUEST = 'UPDATE_PROJECT_DETAILS_REQUEST'
export const UPDATE_PROJECT_DETAILS_SUCCESS = 'UPDATE_PROJECT_DETAILS_SUCCESS'
export const UPDATE_PROJECT_DETAILS_FAIL =    'UPDATE_PROJECT_DETAILS_FAIL'