export const GET_USER_DETAILS_REQUEST ='GET_USER_DETAILS_REQUEST'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE'

export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST'
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS'
export const UPDATE_USER_DETAILS_FAILURE = 'UPDATE_USER_DETAILS_FAILURE'

export const GET_ALL_EDUCATION_REQUEST = 'GET_ALL_EDUCATION_REQUEST'
export const GET_ALL_EDUCATION_SUCCESS = 'GET_ALL_EDUCATION_SUCCESS'
export const GET_ALL_EDUCATION_FAILURE = 'GET_ALL_EDUCATION_FAILURE'


export const GET_EDUCATION_BY_ID_REQUEST = 'GET_EDUCATION_REQUEST'
export const GET_EDUCATION_BY_ID_SUCCESS = 'GET_EDUCATION_SUCCESS'
export const GET_EDUCATION_BY_ID_FAILURE = 'GET_EDUCATION_FAILURE'

export const ADD_NEW_EDUCATION_REQUEST = 'ADD_NEW_EDUCATION_REQUEST'
export const ADD_NEW_EDUCATION_SUCCESS = 'ADD_NEW_EDUCATION_SUCCESS'
export const ADD_NEW_EDUCATION_FAILURE = 'ADD_NEW_EDUCATION_FAILURE'

export const UPDATE_EDUCATION_REQUEST = 'UPDATE_EDUCATION_REQUEST'
export const UPDATE_EDUCATION_SUCCESS = 'UPDATE_EDUCATION_SUCCESS'
export const UPDATE_EDUCATION_FAILURE = 'UPDATE_EDUCATION_FAILURE'

export const DELETE_EDUCATION_REQUEST = 'DELETE_EDUCATION_REQUEST'
export const DELETE_EDUCATION_SUCCESS = 'DELETE_EDUCATION_SUCCESS'
export const DELETE_EDUCATION_FAILURE = 'DELETE_EDUCATION_FAILURE'

export const GET_EXPERIENCE_REQUEST = 'GET_EXPERIENCE_REQUEST'
export const GET_EXPERIENCE_SUCCESS = 'GET_EXPERIENCE_SUCCESS'
export const GET_EXPERIENCE_FAILURE = 'GET_EXPERIENCE_FAILURE'

export const GET_ALL_EXPERIENCE_REQUEST = 'GET_ALL_EXPERIENCE_REQUEST'
export const GET_ALL_EXPERIENCE_SUCCESS = 'GET_ALL_EXPERIENCE_SUCCESS'
export const GET_ALL_EXPERIENCE_FAILURE = 'GET_ALL_EXPERIENCE_FAILURE'

export const UPDATE_EXPERIENCE_REQUEST = 'UPDATE_EXPERIENCE_REQUEST'
export const UPDATE_EXPERIENCE_SUCCESS = 'UPDATE_EXPERIENCE_SUCCESS'
export const UPDATE_EXPERIENCE_FAILURE = 'UPDATE_EXPERIENCE_FAILURE'

export const ADD_NEW_EXPERIENCE_REQUEST = 'ADD_NEW_EXPERIENCE_REQUEST'
export const ADD_NEW_EXPERIENCE_SUCCESS = 'ADD_NEW_EXPERIENCE_SUCCESS'
export const ADD_NEW_EXPERIENCE_FAILURE = 'ADD_NEW_EXPERIENCE_FAILURE'

export const DELETE_EXPERIENCE_REQUEST = 'DELETE_EXPERIENCE_REQUEST'
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS'
export const DELETE_EXPERIENCE_FAILURE = 'DELETE_EXPERIENCE_FAILURE'


export const GET_ALL_CERTIFICATE_REQUEST = 'GET_ALL_CERTIFICATE_REQUEST'
export const GET_ALL_CERTIFICATE_SUCCESS = 'GET_ALL_CERTIFICATE_SUCCESS'
export const GET_ALL_CERTIFICATE_FAILURE = 'GET_ALL_CERTIFICATE_FAILURE'

export const GET_CERTIFICATE_REQUEST = 'GET_CERTIFICATE_REQUEST'
export const GET_CERTIFICATE_SUCCESS = 'GET_CERTIFICATE_SUCCESS'
export const GET_CERTIFICATE_FAILURE = 'GET_CERTIFICATE_FAILURE'

export const UPDATE_CERTIFICATE_REQUEST = 'UPDATE_CERTIFICATE_REQUEST'
export const UPDATE_CERTIFICATE_SUCCESS = 'UPDATE_CERTIFICATE_SUCCESS'
export const UPDATE_CERTIFICATE_FAILURE = 'UPDATE_CERTIFICATE_FAILURE'

export const ADD_NEW_CERTIFICATE_REQUEST = 'ADD_NEW_CERTIFICATE_REQUEST'
export const ADD_NEW_CERTIFICATE_SUCCESS = 'ADD_NEW_CERTIFICATE_SUCCESS'
export const ADD_NEW_CERTIFICATE_FAILURE = 'ADD_NEW_CERTIFICATE_FAILURE'

export const DELETE_CERTIFICATE_REQUEST = 'DELETE_CERTIFICATE_REQUEST'
export const DELETE_CERTIFICATE_SUCCESS = 'DELETE_CERTIFICATE_SUCCESS'
export const DELETE_CERTIFICATE_FAILURE = 'DELETE_CERTIFICATE_FAILURE'