import {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
   
    SIGNUP_REQUEST,
    SIGNUP_SUCCESS,
    SIGNUP_FAILURE,
   
    CHANGE_PASSWORD_REQUEST,
    CHANGE_PASSWORD_SUCCESS,
    CHANGE_PASSWORD_FAILURE,
   
    RESET_PASSWORD_REQUEST,
    RESET_PASSWORD_SUCCESS,
    RESET_PASSWORD_FAILURE,
   
    FORGET_PASSWORD_REQUEST,
    FORGET_PASSWORD_SUCCESS,
    FORGET_PASSWORD_FAILURE,
   
    FILL_BASIC_DETAILS_REQUEST,
    FILL_BASIC_DETAILS_SUCCESS,
    FILL_BASIC_DETAILS_FAILURE,
   
    UPDATE_PROFILE_IMAGE_REQUEST,
    UPDATE_PROFILE_IMAGE_SUCESS,
    UPDATE_PROFILE_IMAGE_FAILURE,
   
    UPDATE_USERNAME_REQUEST,
    UPDATE_USERNAME_SUCCESS,
    UPDATE_USERNAME_FAIL,
   
    UPDATE_SOCIAL_ACCOUNT_REQUEST,
    UPDATE_SOCIAL_ACCOUNT_SUCCESS,
    UPDATE_SOCIAL_ACCOUNT_FAIL,  
   
} from './../constant/authConstants'